config/routes.rb
BanzenaFinder::Application.routes.draw do
  resources :banzenas

  match 'banzenas_name' => 'banzenas#banzenas_name'

  root :to => 'banzenas#index'

end

app/models/banzena.rb
class Banzena < ActiveRecord::Base
	def self.banzenas_name
		Banzena.select(:name).uniq
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/banzenas_controller.rb
class BanzenasController < ApplicationController
  # GET /banzenas
  # GET /banzenas.json
  def index
    @banzenas = Banzena.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @banzenas }
    end
  end

  # GET /banzenas/1
  # GET /banzenas/1.json
  def show
    @banzena = Banzena.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @banzena }
    end
  end

  # GET /banzenas/new
  # GET /banzenas/new.json
  def new
    @banzena = Banzena.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @banzena }
    end
  end

  # GET /banzenas/1/edit
  def edit
    @banzena = Banzena.find(params[:id])
  end

  # POST /banzenas
  # POST /banzenas.json
  def create
    @banzena = Banzena.new(params[:banzena])

    respond_to do |format|
      if @banzena.save
        format.html { redirect_to @banzena, notice: 'Banzena was successfully created.' }
        format.json { render json: @banzena, status: :created, location: @banzena }
      else
        format.html { render action: "new" }
        format.json { render json: @banzena.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /banzenas/1
  # PUT /banzenas/1.json
  def update
    @banzena = Banzena.find(params[:id])

    respond_to do |format|
      if @banzena.update_attributes(params[:banzena])
        format.html { redirect_to @banzena, notice: 'Banzena was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @banzena.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banzenas/1
  # DELETE /banzenas/1.json
  def destroy
    @banzena = Banzena.find(params[:id])
    @banzena.destroy

    respond_to do |format|
      format.html { redirect_to banzenas_url }
      format.json { head :no_content }
    end
  end

#banzenas_name
  def banzenas_name
    @banzena=Banzena.banzenas_name
    render json:@banzena
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banzenas_helper.rb
module BanzenasHelper
end

app/views/banzenas/_form.html.erb
<%= form_for(@banzena) do |f| %>
  <% if @banzena.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banzena.errors.count, "error") %> prohibited this banzena from being saved:</h2>

      <ul>
      <% @banzena.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :has_80? %><br />
    <%= f.check_box :has_80? %>
  </div>
  <div class="field">
    <%= f.label :has_90? %><br />
    <%= f.check_box :has_90? %>
  </div>
  <div class="field">
    <%= f.label :has_92? %><br />
    <%= f.check_box :has_92? %>
  </div>
  <div class="field">
    <%= f.label :has_95? %><br />
    <%= f.check_box :has_95? %>
  </div>
  <div class="field">
    <%= f.label :has_gas? %><br />
    <%= f.check_box :has_gas? %>
  </div>
  <div class="field">
    <%= f.label :has_solar? %><br />
    <%= f.check_box :has_solar? %>
  </div>
  <div class="field">
    <%= f.label :counter_80 %><br />
    <%= f.number_field :counter_80 %>
  </div>
  <div class="field">
    <%= f.label :counter_90 %><br />
    <%= f.number_field :counter_90 %>
  </div>
  <div class="field">
    <%= f.label :counter_92 %><br />
    <%= f.number_field :counter_92 %>
  </div>
  <div class="field">
    <%= f.label :counter_95 %><br />
    <%= f.number_field :counter_95 %>
  </div>
  <div class="field">
    <%= f.label :counter_gas %><br />
    <%= f.number_field :counter_gas %>
  </div>
  <div class="field">
    <%= f.label :counter_solar %><br />
    <%= f.number_field :counter_solar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banzenas/edit.html.erb
<h1>Editing banzena</h1>

<%= render 'form' %>

<%= link_to 'Show', @banzena %> |
<%= link_to 'Back', banzenas_path %>

app/views/banzenas/index.html.erb
<h1>Listing banzenas</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Telephone</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Has 80?</th>
    <th>Has 90?</th>
    <th>Has 92?</th>
    <th>Has 95?</th>
    <th>Has gas?</th>
    <th>Has solar?</th>
    <th>Counter 80</th>
    <th>Counter 90</th>
    <th>Counter 92</th>
    <th>Counter 95</th>
    <th>Counter gas</th>
    <th>Counter solar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banzenas.each do |banzena| %>
  <tr>
    <td><%= banzena.name %></td>
    <td><%= banzena.description %></td>
    <td><%= banzena.address %></td>
    <td><%= banzena.telephone %></td>
    <td><%= banzena.longitude %></td>
    <td><%= banzena.latitude %></td>
    <td><%= banzena.has_80? %></td>
    <td><%= banzena.has_90? %></td>
    <td><%= banzena.has_92? %></td>
    <td><%= banzena.has_95? %></td>
    <td><%= banzena.has_gas? %></td>
    <td><%= banzena.has_solar? %></td>
    <td><%= banzena.counter_80 %></td>
    <td><%= banzena.counter_90 %></td>
    <td><%= banzena.counter_92 %></td>
    <td><%= banzena.counter_95 %></td>
    <td><%= banzena.counter_gas %></td>
    <td><%= banzena.counter_solar %></td>
    <td><%= link_to 'Show', banzena %></td>
    <td><%= link_to 'Edit', edit_banzena_path(banzena) %></td>
    <td><%= link_to 'Destroy', banzena, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Banzena', new_banzena_path %>

app/views/banzenas/new.html.erb
<h1>New banzena</h1>

<%= render 'form' %>

<%= link_to 'Back', banzenas_path %>

app/views/banzenas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @banzena.name %>
</p>

<p>
  <b>Description:</b>
  <%= @banzena.description %>
</p>

<p>
  <b>Address:</b>
  <%= @banzena.address %>
</p>

<p>
  <b>Telephone:</b>
  <%= @banzena.telephone %>
</p>

<p>
  <b>Longitude:</b>
  <%= @banzena.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @banzena.latitude %>
</p>

<p>
  <b>Has 80?:</b>
  <%= @banzena.has_80? %>
</p>

<p>
  <b>Has 90?:</b>
  <%= @banzena.has_90? %>
</p>

<p>
  <b>Has 92?:</b>
  <%= @banzena.has_92? %>
</p>

<p>
  <b>Has 95?:</b>
  <%= @banzena.has_95? %>
</p>

<p>
  <b>Has gas?:</b>
  <%= @banzena.has_gas? %>
</p>

<p>
  <b>Has solar?:</b>
  <%= @banzena.has_solar? %>
</p>

<p>
  <b>Counter 80:</b>
  <%= @banzena.counter_80 %>
</p>

<p>
  <b>Counter 90:</b>
  <%= @banzena.counter_90 %>
</p>

<p>
  <b>Counter 92:</b>
  <%= @banzena.counter_92 %>
</p>

<p>
  <b>Counter 95:</b>
  <%= @banzena.counter_95 %>
</p>

<p>
  <b>Counter gas:</b>
  <%= @banzena.counter_gas %>
</p>

<p>
  <b>Counter solar:</b>
  <%= @banzena.counter_solar %>
</p>


<%= link_to 'Edit', edit_banzena_path(@banzena) %> |
<%= link_to 'Back', banzenas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BanzenaFinder</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>